### ISSUE TITLE
sunrise-core v0.38.3 have empty chain-id

### ISSUE THREAD

**Issue by Senna46** [SunriseLayer/sunrise-app#3]
Empty chain-id is an error in sdk v0.50.2. `sunrise-core` needs to be fixed.

https://github.com/sunrise-zone/sunrise-app/pull/1#issuecomment-1943227381

**Comment by Senna46** [comment]
Fixed chain-id problem
https://github.com/SunriseLayer/sunrise-app/commit/d0f85289f87a446221d7af9c1fd6bc5d05d4811b

but got error
```panic: test timed out after 30s
running tests:
	TestMaliciousTestNode (30s)

goroutine 162 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive]:
testing.(*T).Run(0xc001582340, {0x3172751?, 0x53b73c?}, 0x3a63280)
	/usr/local/go/src/testing/testing.go:1649 +0x3c8
testing.runTests.func1(0x5da5f00?)
	/usr/local/go/src/testing/testing.go:2054 +0x3e
testing.tRunner(0xc001582340, 0xc00133bc48)
	/usr/local/go/src/testing/testing.go:1595 +0xff
testing.runTests(0xc000145180?, {0x5c63500, 0x2, 0x2}, {0xc0009a85b0?, 0xc00133bd08?, 0x5d9e420?})
	/usr/local/go/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc000145180)
	/usr/local/go/src/testing/testing.go:1925 +0x636
main.main()
	_testmain.go:49 +0x19c

goroutine 5 [select]:
github.com/desertbit/timer.timerRoutine()
	/home/user/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0xb2
created by github.com/desertbit/timer.init.0 in goroutine 1
	/home/user/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x1a

goroutine 52 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0005c7e00)
	/home/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/home/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 54 [sleep]:
time.Sleep(0xb2d05e00)
	/usr/local/go/src/runtime/time.go:195 +0x125
github.com/cometbft/cometbft/abci/client.(*socketClient).OnStart(0xc0004b9680)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/abci/client/socket_client.go:82 +0x5e
github.com/cometbft/cometbft/libs/service.(*BaseService).Start(0xc0004b9680)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/libs/service/service.go:144 +0x2f5
github.com/cometbft/cometbft/proxy.(*multiAppConn).abciClientFor(0xc0013fe2a0, {0x315033c, 0x5})
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/proxy/multi_app_conn.go:189 +0x1af
github.com/cometbft/cometbft/proxy.(*multiAppConn).OnStart(0xc0013fe2a0)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/proxy/multi_app_conn.go:88 +0x28
github.com/cometbft/cometbft/libs/service.(*BaseService).Start(0xc0013fe2a0)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/libs/service/service.go:144 +0x2f5
github.com/cometbft/cometbft/node.createAndStartProxyAppConns({0x3fd9fc0?, 0xc0032f81b0}, {0x40102b8, 0x5dd91c0}, 0xc002325770)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/node/setup.go:126 +0x1e9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x400fb48, 0x5dd91c0}, 0xc00089ea00, {0x3ff0070, 0xc000eab860}, 0xc0030eed20, {0x3fd9fc0, 0xc0032f81b0}, 0x4?, 0x3a63c00, ...)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/node/node.go:315 +0x305
github.com/cometbft/cometbft/node.NewNode(0x3a?, {0x3ff0070?, 0xc000eab860?}, 0xc00048c000?, {0x3fd9fc0?, 0xc0032f81b0?}, 0x0?, 0xc000be4380?, 0x35?, {0x40102b8, ...}, ...)
	/home/user/go/pkg/mod/github.com/sunrise-zone/sunrise-core@v0.38.3-0.20240308143202-da7badb2aa06/node/node.go:270 +0xa9
github.com/sunrise-zone/sunrise-app/test/util/testnode.NewCometNode({0xc000be4380, 0x35}, 0xc0011b4248)
	/home/user/github.com/sunrise-zone/sunrise-app/test/util/testnode/full_node.go:41 +0x4cb
github.com/sunrise-zone/sunrise-app/test/util/testnode.NewNetwork({_, _}, _)
	/home/user/github.com/sunrise-zone/sunrise-app/test/util/testnode/network.go:34 +0x328
github.com/sunrise-zone/sunrise-app/test/util/malicious.TestMaliciousTestNode(0xc0015824e0)
	/home/user/github.com/sunrise-zone/sunrise-app/test/util/malicious/app_test.go:76 +0x1af
testing.tRunner(0xc0015824e0, 0x3a63280)
	/usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1648 +0x3ad
```

**Comment by Senna46** [comment]
reverted

add chain-id to appOption, but does not work...
https://github.com/SunriseLayer/sunrise-app/commit/a6fd2776a7daa96707d56840486a47eeb169d3cb#diff-649e3327558221d8b5e72c171eb88beea8c086163839c6f3b04313fa8c95f553R33

**Comment by Senna46** [comment]
but got many errors

here is one of them
```
goroutine 66 [select]:
github.com/cosmos/cosmos-sdk/server/grpc.StartGRPCServer({0x3ff50f8, 0x5db0180}, {0x3ff74a0, 0x5db0180}, {0x1, {0xc002787de0, 0xf}, 0xa00000, 0x7fffffff}, 0xc001735e00)
        /home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.2/server/grpc/server.go:94 +0x2e5
github.com/sunrise-zone/sunrise-app/test/util/testnode.StartGRPCServer({_, _}, _, {{0x3ff50f8, 0x5db0180}, {{0x0, 0x0, 0x0}, {0x4015bc8, 0xc0024bd410}, ...}, ...})
        /home/user/github.com/sunrise-zone/sunrise-app/test/util/testnode/rpc_client.go:64 +0x1d9
github.com/sunrise-zone/sunrise-app/test/util/testnode.NewNetwork({_, _}, _)
        /home/user/github.com/sunrise-zone/sunrise-app/test/util/testnode/network.go:47 +0x6cc
github.com/sunrise-zone/sunrise-app/test/util/malicious.TestMaliciousTestNode(0xc0014124e0)
        /home/user/github.com/sunrise-zone/sunrise-app/test/util/malicious/app_test.go:74 +0x12a
testing.tRunner(0xc0014124e0, 0x3a4a518)
        /usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1648 +0x3ad
```

**Comment by Senna46** [comment]
Put  `StartGRPCServer()` in gorouting and solve this error
https://github.com/SunriseLayer/sunrise-app/pull/4

ref https://github.com/cosmos/cosmos-sdk/blob/v0.50.2/server/start.go#L527-L529
